name: 'coverage'
on:
  pull_request:
    branches:
      - main
jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          test-script: yarn test
          output: comment, report-markdown
      - name: Create test-coverage.md file
        run: |
          echo '${{ steps.coverage.outputs.report }}' > test-coverage.md
      - name: Commit and push test-coverage.md
        run: |
          git checkout main
          git add test-coverage.md
          git commit -m "Add test coverage report"
          git push origin main
