name: 'coverage'
on:
  pull_request:
    branches:
      - main
      - dev
permissions:
  checks: write
  pull-requests: write
  contents: write
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          package-manager: yarn
          test-script: yarn test
          output: comment, report-markdown
